FROM easypi/openwrt:bcm2710

#RUN /bin/bash

# RUN cd ~/sdk && sudo chmod 777 bin
# RUN ./scripts/feeds update -a && \\
#     ./scripts/feeds install -a && \\
#     make defconfig && \\
#     IGNORE_ERRORS=1 make V=s

CMD ["/bin/bash"]