apiVersion: v1
kind: Service
metadata:
  name: echo1
spec:
  type: NodePort
  ports:
  - port: 8090
    targetPort: 5678
    nodePort: 31000
    
  selector:
    app: echo1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo1
spec:
  selector:
    matchLabels:
      app: echo1
  replicas: 2
  template:
    metadata:
      labels:
        app: echo1
    spec:
      containers:
      - name: echo1
        image: hashicorp/http-echo
        args:
        - "-text=echo1"
        ports:
        - containerPort: 5678
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec: 
  rules:
  - http:
      paths:
      - path: /echo
        backend:
          serviceName: echo1
          servicePort: 8090    
