apiVersion: v1
kind: Service
metadata:
  name: influxdb-deploy
spec:
  type: NodePort
  ports:
    - name: api
      nodePort: 30086
      port: 8086 # api
      targetPort: 8086
    - name: rpc
      nodePort: 30088
      port: 8088 # rpc
      targetPort: 8088
