persistence:
  enabled: true
  size: 80Gi
service:
  type: NodePort
  ports:
  - port: 8096          # api
    targetPort: 8086    
    nodePort: 31001
  - port: 8098          # rpc
    targetPort: 8088    
    nodePort: 31003

# config:
#   admin:
#     enabled: true
#     bind_address: 8083

# ingress:
#   enabled: true
#   tls: false
